# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "site"
destination:    ./_site
host:           "localhost"
port:           9001
baseurl:        "/bootstrap"
url:            "http://digital.arizona.edu/bootstrap"
encoding:       UTF-8
exclude:
  - docs/0.0/assets/scss/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              "Arizona Bootstrap"
description:        "University of Arizona theme for Bootstrap."
authors:            "Arizona Digital contributors"
social_image_path:  /docs/0.0/assets/brand/bootstrap-social.png
social_logo_path:   /docs/0.0/assets/brand/bootstrap-social-logo.png

# Custom variables
current_version:      0.0.2
current_ruby_version: 0.0.2
docs_version:         0.0
repo:                 "https://github.com/az-digital/arizona-bootstrap"
slack:                "/about/get-involved/#connect-with-us-on-slack"
azdigital:            "https://digital.arizona.edu"
az_quickstart:           "https://github.com/az-digital/az_quickstart"

download:
  source:           "https://github.com/az-digital/arizona-bootstrap/archive/master.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  jquery:           "https://code.jquery.com/jquery-3.4.1.slim.min.js"
  jquery_hash:      "sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
  popper:           "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  popper_hash:      "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"

toc:
  min_level:        2
  max_level:        4
  no_toc_section_class:
    - "bd-callout"
    - "bd-example"
