# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "site"
destination:    ./_site
host:           "{{az_site_host}}"
port:           9001
baseurl:        "{{az_site_base_url}}"
encoding:       UTF-8
exclude:
  - "docs/{{az_site_docs_version}}/assets/scss/"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              "Arizona Bootstrap"
description:        "University of Arizona theme for Bootstrap."
authors:            "Arizona Digital contributors"
social_image_path:  "{{az_site_base_url}}/docs/{{az_short_version}}/assets/brand/bootstrap-social.png"
social_logo_path:   "{{az_site_base_url}}/docs/{{az_short_version}}/assets/brand/bootstrap-social-logo.png"

# Custom variables
current_version:      "{{az_version}}"
docs_version:         "{{az_short_version}}"
repo:                 "https://github.com/az-digital/arizona-bootstrap"
slack:                "/about/get-involved/#connect-with-us-on-slack"
azdigital:            "https://digital.arizona.edu"
az_quickstart:        "https://github.com/az-digital/az_quickstart"

download:
  source:           "https://github.com/az-digital/arizona-bootstrap/archive/v{{az_version}}.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              "https://cdn.digital.arizona.edu/lib/arizona-bootstrap/{{az_version}}/css/arizona-bootstrap.min.css"
  js:               "https://cdn.digital.arizona.edu/lib/arizona-bootstrap/{{az_version}}/js/arizona-bootstrap.min.js"
  js_bundle:        "https://cdn.digital.arizona.edu/lib/arizona-bootstrap/{{az_version}}/js/arizona-bootstrap.bundle.min.js"
  jquery:           "https://code.jquery.com/jquery-3.5.1.slim.min.js"
  jquery_hash:      "sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
  popper:           "https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  popper_hash:      "sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"

toc:
  min_level:        2
  max_level:        4
  no_toc_section_class:
    - "bd-callout"
    - "bd-example"
