# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "site"
destination:    ./_gh_pages
host:           "localhost"
port:           9001
baseurl:        ""
url:            "http://uadigital.arizona.edu/arizona-bootstrap"
encoding:       UTF-8
exclude:
  - docs/0.0/assets/scss/

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

# Social
title:              "Arizona Bootstrap"
description:        "University of Arizona theme for Bootstrap."
authors:            "UA Digital contributors"
social_image_path:  /docs/0.0/assets/brand/bootstrap-social.png
social_logo_path:   /docs/0.0/assets/brand/bootstrap-social-logo.png

# Custom variables
current_version:      0.0.1
current_ruby_version: 0.0.1
docs_version:         0.0
repo:                 "https://bitbucket.org/uadigital/arizona-bootstrap"
slack:                "https://quickstart.arizona.edu/join-us-on-slack"
quickstart:           "https://quickstart.arizona.edu"

download:
  source:           "https://bitbucket.org/uadigital/arizona-bootstrap/get/v0.0.1.zip"
  dist:             "https://bitbucket.org/uadigital/arizona-bootstrap/downloads/arizona-bootstrap-v0.0.1.zip"

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:              "https://cdn.uadigital.arizona.edu/lib/arizona-bootstrap/v0.0.1/arizona-bootstrap.min.css"
  js:               "https://cdn.uadigital.arizona.edu/lib/arizona-bootstrap/v0.0.1/arizona-bootstrap.min.js"
  js_bundle:        "https://cdn.uadigital.arizona.edu/lib/arizona-bootstrap/v0.0.1/arizona-bootstrap.bundle.min.js"
  jquery:           "https://code.jquery.com/jquery-3.4.1.slim.min.js"
  jquery_hash:      "sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
  popper:           "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js"
  popper_hash:      "sha384-L2pyEeut/H3mtgCBaUNw7KWzp5n9+4pDQiExs933/5QfaTh8YStYFFkOzSoXjlTb"

toc:
  min_level:        2
  max_level:        4
  no_toc_section_class:
    - "bd-callout"
    - "bd-example"
