image: uadigital/arizona-node-base:0.0.2
definitions:
  caches:
    bundler: vendor/bundle
  steps:
    - step: &install
        name: Install dependencies
        caches:
          - node
          - bundler
        artifacts:
          - .bundle/**
          - node_modules/**
          - vendor/bundle/**
        script:
          - npm install
          - bundle install --deployment
pipelines:
  tags:
    '*':
      - step: *install
      - step:
          name: Deploy assets to CDN
          script:
            - npm run dist
            - aws configure set preview.cloudfront true
            - aws s3 sync --cache-control max-age=691200 dist/ s3://${AWS_S3_BUCKET_CDN}/lib/arizona-bootstrap/${BITBUCKET_TAG}/
            - aws s3 sync --cache-control max-age=691200 dist/ s3://${AWS_S3_BUCKET_CDN}/lib/arizona-bootstrap/latest/
            - aws cloudfront create-invalidation --distribution-id $CF_DISTRO_ID --paths /lib/arizona-bootstrap/latest/*
      - step:
          name: Build & deploy review sites
          script:
            - npm run dist
            - export UAZ_REVIEW_BASEURL=/arizona-bootstrap-review/${BITBUCKET_TAG}
            - npm run docs-review
            - aws s3 sync _site/ s3://${AWS_S3_BUCKET}/arizona-bootstrap-review/${BITBUCKET_TAG}/
            - export UAZ_REVIEW_BASEURL=/arizona-bootstrap-review/latest
            - npm run docs-review
            - aws s3 sync _site/ s3://${AWS_S3_BUCKET}/arizona-bootstrap-review/latest/
      - step:
          name: Build & deploy documentation site
          script:
            - npm run dist
            - export JEKYLL_ENV=production
            - npm run docs
            - aws s3 sync --cache-control max-age=691200 _site/ s3://${AWS_S3_BUCKET_UADIGITAL}/arizona-bootstrap/

  branches:
    master:
      - step: *install
      - step:
          name: Deploy assets to CDN
          script:
            - npm run dist
            - aws configure set preview.cloudfront true
            - aws s3 sync --cache-control max-age=691200 dist/ s3://${AWS_S3_BUCKET_CDN}/lib/arizona-bootstrap/master/
            - aws cloudfront create-invalidation --distribution-id $CF_DISTRO_ID --paths /lib/arizona-bootstrap/master/*
      - step:
          name: Build & deploy documentation site
          script:
            - npm run dist
            - export UAZ_REVIEW_BASEURL=/arizona-bootstrap-review/master
            - npm run docs-review
            - aws s3 sync _site/ s3://${AWS_S3_BUCKET}/arizona-bootstrap-review/master/
    UADIGITAL*:
      - step: *install
      - step:
          name: Build & deploy review site
          script:
            - npm run dist
            - export UAZ_REVIEW_BASEURL="/arizona-bootstrap-review/${BITBUCKET_BRANCH}"
            - npm run docs-review
            - aws s3 sync _site/ s3://${AWS_S3_BUCKET}/arizona-bootstrap-review/${BITBUCKET_BRANCH}/
