image: uadigital/arizona-node-base:0.0.2
definitions:
  caches:
    bundler: vendor/bundle
  steps:
    - step: &install
        name: Install dependencies
        caches:
          - node
          - bundler
        artifacts:
          - .bundle/**
          - node_modules/**
          - vendor/bundle/**
        script:
          - npm install
          - bundle install --deployment
pipelines:
  tags:
    '*':
      - step: *install
      - step:
          name: Deploy assets to CDN
          script:
            - npm run dist
            - aws configure set preview.cloudfront true
            - aws s3 sync --cache-control max-age=691200 dist/ s3://${AWS_S3_BUCKET_CDN}/lib/arizona-bootstrap/${BITBUCKET_TAG}/
            - aws s3 sync --cache-control max-age=691200 dist/ s3://${AWS_S3_BUCKET_CDN}/lib/arizona-bootstrap/latest/
            - aws cloudfront create-invalidation --distribution-id $CF_DISTRO_ID --paths /lib/arizona-bootstrap/latest/*
      - step:
          name: Build & deploy review sites
          script:
            - npm run dist
            - export UAZ_REVIEW_BASEURL=/arizona-bootstrap/${BITBUCKET_TAG}
            - npm run docs-review
            - aws s3 sync --delete _site/ s3://${AWS_S3_BUCKET_REVIEW}/arizona-bootstrap/${BITBUCKET_TAG}/
            - aws cloudfront create-invalidation --distribution-id ${REVIEW_CF_DISTRO_ID} --paths /arizona-bootstrap/${BITBUCKET_TAG}/*
            - export UAZ_REVIEW_BASEURL=/arizona-bootstrap/latest
            - npm run docs-review
            - aws s3 sync --delete _site/ s3://${AWS_S3_BUCKET_REVIEW}/arizona-bootstrap/latest/
            - aws cloudfront create-invalidation --distribution-id ${REVIEW_CF_DISTRO_ID} --paths /arizona-bootstrap/latest/*
      - step:
          name: Build & deploy documentation site
          script:
            - npm run dist
            - export JEKYLL_ENV=production
            - npm run docs
            - aws s3 sync --cache-control max-age=691200 _site/ s3://${AWS_S3_BUCKET_UADIGITAL}/arizona-bootstrap/

  branches:
    master:
      - step: *install
      - step:
          name: Deploy assets to CDN
          script:
            - npm run dist
            - aws configure set preview.cloudfront true
            - aws s3 sync --cache-control max-age=691200 dist/ s3://${AWS_S3_BUCKET_CDN}/lib/arizona-bootstrap/master/
            - aws cloudfront create-invalidation --distribution-id $CF_DISTRO_ID --paths /lib/arizona-bootstrap/master/*
      - step:
          name: Build & deploy documentation site
          script:
            - npm run dist
            - export UAZ_REVIEW_BASEURL=/arizona-bootstrap/master
            - npm run docs-review
            - aws s3 sync --delete _site/ s3://${AWS_S3_BUCKET_REVIEW}/arizona-bootstrap/master/
            - aws cloudfront create-invalidation --distribution-id ${REVIEW_CF_DISTRO_ID} --paths /arizona-bootstrap/master/*
            - export S3_URL="${S3_REVIEW_URL}/master"
            - export BUILD_STATUS="{\"key\":\"review\", \"state\":\"SUCCESSFUL\", \"name\":\"Review Site\", \"url\":\"${S3_URL}\"}"
            - curl -H "Content-Type:application/json" -X POST --user "${BB_AUTH_STRING}" -d "${BUILD_STATUS}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/commit/${BITBUCKET_COMMIT}/statuses/build"
    UADIGITAL*:
      - step: *install
      - step:
          name: Build & deploy review site
          script:
            - npm run dist
            - export UAZ_REVIEW_BASEURL="/arizona-bootstrap/${BITBUCKET_BRANCH}"
            - npm run docs-review
            - aws s3 sync --delete _site/ s3://${AWS_S3_BUCKET_REVIEW}/arizona-bootstrap/${BITBUCKET_BRANCH}/
            - aws cloudfront create-invalidation --distribution-id ${REVIEW_CF_DISTRO_ID} --paths /arizona-bootstrap/${BITBUCKET_BRANCH}/*
            - export S3_URL="${S3_REVIEW_URL}/${BITBUCKET_BRANCH}"
            - export BUILD_STATUS="{\"key\":\"review\", \"state\":\"SUCCESSFUL\", \"name\":\"Review Site\", \"url\":\"${S3_URL}\"}"
            - curl -H "Content-Type:application/json" -X POST --user "${BB_AUTH_STRING}" -d "${BUILD_STATUS}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/commit/${BITBUCKET_COMMIT}/statuses/build"

