image: uadigital/arizona-node-base:0.0.2
pipelines:
  tags:
    '*':
      - step:
          caches:
            - node
          script:
            - npm install
            - bundle install
            - npm run dist
            - npm run docs
            - export access_token=$(curl -s -X POST -u "${CLIENT_ID}:${CLIENT_SECRET}" https://bitbucket.org/site/oauth2/access_token -d grant_type=client_credentials -d scopes="repository"| jq --raw-output '.access_token')
            - aws configure set preview.cloudfront true
            - aws s3 sync --cache-control max-age=691200 dist/ s3://${AWS_S3_BUCKET_CDN}/lib/arizona-bootstrap/${BITBUCKET_TAG}/
            - aws s3 sync --cache-control max-age=691200 dist/ s3://${AWS_S3_BUCKET_CDN}/lib/arizona-bootstrap/latest/
            - aws s3 sync _site/ s3://${AWS_S3_BUCKET}/arizona-bootstrap-review/${BITBUCKET_TAG}/
            - aws s3 sync _site/ s3://${AWS_S3_BUCKET}/arizona-bootstrap-review/latest/
            - aws s3 sync --cache-control max-age=691200 _site/ s3://${AWS_S3_BUCKET_UADIGITAL}/arizona-bootstrap/
            - aws cloudfront create-invalidation --distribution-id $CF_DISTRO_ID --paths /lib/arizona-bootstrap/latest/*
            - git config --global user.name "$BITBUCKET_REPO_OWNER"
            - git config --global user.email "noreply@bitbucket.org"

  branches:
    master:
      - step:
          caches:
            - node
          script:
            - npm install
            - bundle install
            - npm run dist
            - aws configure set preview.cloudfront true
            - aws s3 sync --cache-control max-age=691200 dist/ s3://${AWS_S3_BUCKET_CDN}/lib/arizona-bootstrap/master/
            - npm run docs
            - aws s3 sync _site/ s3://${AWS_S3_BUCKET}/arizona-bootstrap-review/master/
            - aws cloudfront create-invalidation --distribution-id $CF_DISTRO_ID --paths /lib/arizona-bootstrap/master/*
    UADIGITAL*:
      - step:
          caches:
            - node
          script:
            - npm install
            - bundle install
            - npm run dist
            - npm run docs
            - export BRANCH=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
            - export COMMIT_MSG=$(git log -1 --pretty=%B)
            - aws s3 sync _site/ s3://${AWS_S3_BUCKET}/arizona-bootstrap-review/${BRANCH}/
