name: 'npm run'
description: 'Run arizona-bootsrap npm scripts'
inputs:
  npm-script:
    description: 'npm script to run'
    required: true
  base-url:
    description: 'Base URL to use when building Jekyll site'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.npm-script }}
    - ${{ inputs.base-url }}
