name: Build & deploy CDN assets

on:
  push:
    branches:
      - master
      - feature/59
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: echo "::set-env name=AZ_TRIMMED_REF::${GITHUB_REF#refs/*/}"

      - name: Build CDN assets
        # uses: actions/github-script@5d03ada4b0a753e9460b312e61cc4f8fdeacf163
        run: |
          docker run --rm -v $(pwd):/arizona-bootstrap azdigital/az-node-jre-jekyll:0.0.2 /arizona-bootstrap/scripts/build-cdn-assets.sh

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b77dc228388218453070969c00c26dc392ecb114
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy CDN assets to S3 + CloudFront
        run: |
            aws s3 sync --cache-control max-age=691200 dist/ s3://${{ secrets.AZ_DIGITAL_CDN_BUCKET }}/lib/arizona-bootstrap/${AZ_TRIMMED_REF}/
            aws cloudfront create-invalidation --distribution-id ${{ secrets.AZ_DIGITAL_CDN }} --paths /lib/arizona-bootstrap/${AZ_TRIMMED_REF}/*

      - name: Deploy CDN assets to S3 + CloudFront (latest)
        if: github.event_name == 'tag'
        run: |
          aws s3 sync --cache-control max-age=691200 dist/ s3://${{ secrets.AZ_DIGITAL_CDN_BUCKET }}/lib/arizona-bootstrap/latest/
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AZ_DIGITAL_CDN }} --paths /lib/arizona-bootstrap/latest/*
