name: Check code for linting errors
on: pull_request

jobs:
  lint-code:
    name: Check code for linting errors
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build variables
        run: |
          echo "::set-env name=AZ_BOOTSTRAP_SOURCE_DIR::arizona-bootstrap-src"
          echo "::set-env name=AZ_DOCKER_IMAGE::$(scripts/build-container.sh)"
      - name: Run the code linting checks
        run: |
          docker run --rm -v $(pwd):/$AZ_BOOTSTRAP_SOURCE_DIR $AZ_DOCKER_IMAGE lint
